config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  resources :child_categories

  resources :brands

  resources :products

  resources :qynqyns

  resources :parent_categories

  resources :posts do
    member do
      post 'comment'
    end
  end

  resources :product_images

  get '/users' => "users#index", as: :user
  get "/user/:name" => "users#show"#, as: :user

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    registrations: "users/registrations",
    passwords:     "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

end

app/models/parent_category.rb
class ParentCategory < ActiveRecord::Base
  has_many :posts
  has_many :child_categories

  validates :name, presence: { message: 'なにか入力して下さい'}
end

app/controllers/parent_categories_controller.rb
class ParentCategoriesController < ApplicationController
  before_action :set_parent_category, only: [:show, :edit, :update, :destroy]

  def index
    @parent_categories = ParentCategory.all
  end

  def show
  end

  def new
    @parent_category = ParentCategory.new
  end

  def edit
  end

  def create
    @parent_category = ParentCategory.new(parent_category_params)

    respond_to do |format|
      if @parent_category.save
        format.html { redirect_to @parent_category, notice: 'Parent Category was successfully created.' }
        format.json { render :show, status: :created, location: @parent_category }
      else
        format.html { render :new }
        format.json { render json: @parent_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @parent_category.update(parent_category_params)
        format.html { redirect_to @parent_category, notice: 'Parent Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent_category }
      else
        format.html { render :edit }
        format.json { render json: @parent_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @parent_category.destroy
    respond_to do |format|
      format.html { redirect_to parent_categories_url, notice: 'Parent Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_parent_category
      @parent_category = ParentCategory.find(params[:id])
    end

    def parent_category_params
      params.require(:parent_category).permit(:name)
    end
end

app/helpers/parent_categories_helper.rb
module ParentCategoriesHelper
end

app/views/parent_categories/_form.html.erb
<%= form_for(@parent_category) do |f| %>
  <% if @parent_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent_category.errors.count, "error") %> prohibited this parent_category from being saved:</h2>

      <ul>
      <% @parent_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parent_categories/edit.html.erb
<h1>Editing parent_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent_category %> |
<%= link_to 'Back', parent_categories_path %>

app/views/parent_categories/index.html.erb
<h1>Listing parent_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parent_categories.each do |parent_category| %>
      <tr>
        <td><%= parent_category.name %></td>
        <td><%= link_to 'Show', parent_category %></td>
        <td><%= link_to 'Edit', edit_parent_category_path(parent_category) %></td>
        <td><%= link_to 'Destroy', parent_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent Category', new_parent_category_path %>

app/views/parent_categories/new.html.erb
<h1>New parent_category</h1>

<%= render 'form' %>

<%= link_to 'Back', parent_categories_path %>

app/views/parent_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent_category.name %>
</p>

<%= link_to 'Edit', edit_parent_category_path(@parent_category) %> |
<%= link_to 'Back', parent_categories_path %>