config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  resources :child_categories

  resources :brands

  resources :products

  resources :qynqyns

  resources :parent_categories

  resources :posts do
    member do
      post 'comment'
    end
  end

  resources :product_images

  get '/users' => "users#index", as: :user
  get "/user/:name" => "users#show"#, as: :user

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    registrations: "users/registrations",
    passwords:     "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

end

app/models/qynqyn.rb
class Qynqyn < ActiveRecord::Base
  has_one :post
  validates :post_id, presence: true, numericality: { only_integer: true }
end

app/controllers/qynqyns_controller.rb
class QynqynsController < ApplicationController
  before_action :set_qynqyn, only: [:show, :edit, :update, :destroy]

  # GET /qynqyns
  # GET /qynqyns.json
  def index
    @qynqyns = Qynqyn.all
  end

  # GET /qynqyns/1
  # GET /qynqyns/1.json
  def show
  end

  # GET /qynqyns/new
  def new
    @qynqyn = Qynqyn.new
  end

  # GET /qynqyns/1/edit
  def edit
  end

  # POST /qynqyns
  # POST /qynqyns.json
  def create
    @qynqyn = Qynqyn.new(qynqyn_params)

    respond_to do |format|
      if @qynqyn.save
        format.html { redirect_to @qynqyn, notice: 'Qynqyn was successfully created.' }
        format.json { render :show, status: :created, location: @qynqyn }
      else
        format.html { render :new }
        format.json { render json: @qynqyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qynqyns/1
  # PATCH/PUT /qynqyns/1.json
  def update
    respond_to do |format|
      if @qynqyn.update(qynqyn_params)
        format.html { redirect_to @qynqyn, notice: 'Qynqyn was successfully updated.' }
        format.json { render :show, status: :ok, location: @qynqyn }
      else
        format.html { render :edit }
        format.json { render json: @qynqyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qynqyns/1
  # DELETE /qynqyns/1.json
  def destroy
    @qynqyn.destroy
    respond_to do |format|
      format.html { redirect_to qynqyns_url, notice: 'Qynqyn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qynqyn
      @qynqyn = Qynqyn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qynqyn_params
      params.require(:qynqyn).permit(:count)
    end
end

app/helpers/qynqyns_helper.rb
module QynqynsHelper
end

app/views/qynqyns/_form.html.erb
<%= form_for(@qynqyn) do |f| %>
  <% if @qynqyn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qynqyn.errors.count, "error") %> prohibited this qynqyn from being saved:</h2>

      <ul>
      <% @qynqyn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qynqyns/edit.html.erb
<h1>Editing qynqyn</h1>

<%= render 'form' %>

<%= link_to 'Show', @qynqyn %> |
<%= link_to 'Back', qynqyns_path %>

app/views/qynqyns/index.html.erb
<h1>Listing qynqyns</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qynqyns.each do |qynqyn| %>
      <tr>
        <td><%= qynqyn.count %></td>
        <td><%= link_to 'Show', qynqyn %></td>
        <td><%= link_to 'Edit', edit_qynqyn_path(qynqyn) %></td>
        <td><%= link_to 'Destroy', qynqyn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qynqyn', new_qynqyn_path %>

app/views/qynqyns/new.html.erb
<h1>New qynqyn</h1>

<%= render 'form' %>

<%= link_to 'Back', qynqyns_path %>

app/views/qynqyns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @qynqyn.count %>
</p>

<%= link_to 'Edit', edit_qynqyn_path(@qynqyn) %> |
<%= link_to 'Back', qynqyns_path %>